site_name: Silvertest
nav:
    - Учащимся:
          - Как найти материал по интересующей теме?: "01-for-students/1.1.md"
          - Как пройти курс по информатике и программированию? : "01-for-students/1.2.md"
          - Как пользоваться учебниками? : "01-for-students/1.3.md"
          - Как тренироваться перед экзаменом? : "01-for-students/1.4.md"
          - Как готовиться к олимпиаде? : "01-for-students/1.5.md"
          - Как попрактиковаться в написании программ? : "01-for-students/1.6.md"
          - Как посмотреть историю своих решений? : "01-for-students/1.7.md"
    - Учителям:
          - Как задать материал ВЛ на дом?: "02-for-teachers/2.1.md"
          - Где посмотреть и проверить результаты учащихся?: "02-for-teachers/2.2.md"
theme:
    name: readthedocs
