site_name: МЭШ.Информатика
nav:
    - Учащимся:
          - Работа по заданию учителя: 
              - Как выполнить ДЗ по информатике?: "01-for-students/1.9.md"
              - Как учитель проверит выполнение задания?: "01-for-students/1.10.md"
              - Где посмотреть результаты выполнения своих заданий?: "01-for-students/1.11.md"
          - Самоподготовка:
              - Как найти материал по интересующей теме?: "01-for-students/1.1.md"
              - Как пройти курс по информатике и программированию? : "01-for-students/1.3.md"
              - Какие типы задач есть в "Виртуальной лаборатории"? : "01-for-students/1.8.md"
              - Как пользоваться учебниками? : "01-for-students/1.2.md"
              - Как тренироваться перед экзаменом? : "01-for-students/1.4.md"
              - Как готовиться к олимпиаде? : "01-for-students/1.5.md"
              - Как посмотреть историю своих решений? : "01-for-students/1.7.md"
              - Как практиковаться в написании программ? : "01-for-students/1.6.md"
    - Учителям:
          - Работа с учащимися:
              - Как задать материал "Виртуальной лаборатории" на дом?: "02-for-teachers/2.1.md"
              - Где посмотреть и проверить результаты учащихся?: "02-for-teachers/2.2.md"
          - Работа с контентом "Виртуальной лаборатории":
              - Как создать свой тест?: "02-for-teachers/2.3.md"
              - Как добавить свою задачу?: "02-for-teachers/2.4.md"
              - Как расширить список компетенций?: "02-for-teachers/2.5.md"
    
          

theme:
    name: readthedocs
